
name: update

on:
  schedule:
    - cron:  '0 0 1 * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Update dependency
        uses: hasundue/molt-action@v1-rc

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Run test
        run: deno test
